# Generated by Django 6.0.7 on 2026-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('unlock_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('sealed', 'Sealed'), ('unlocked', 'Unlocked'), ('delivered', 'Delivered')], default='sealed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['unlock_at'],
            },
        ),
    ]
